name: test

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make

    - name: rax-test
      run: |
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:./"
        make rax-test
        ./rax-test

    - name: rax-oom-test
      run: |
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:./"
        make rax-oom-test
        ./rax-oom-test

  build-qemu:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: arm
            arch: armv7
          - target: aarch64
            arch: aarch64
          - target: ppc64v2
            arch: ppc64le
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends build-essential
          run: |
            make
            LD_LIBRARY_PATH=$PWD make rax-test
            LD_LIBRARY_PATH=$PWD ./rax-test
